spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_service # //localhost:{LOCAL_PORT}/auth_service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
mqtt:
  broker-url: tcp://broker.hivemq.com:1883
  client-id: auth-service
  user-created-topic: users/created