services:
  postgres:
    image: postgres:16
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # {LOCAL_PORT}/{CONTAINER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: